#!/usr/bin/env python3
"""Generate C++ and TypeScript RAD BLE constants from the protocol manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "protocol" / "rad-ble-v1.json"


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def cpp_header(data: dict) -> str:
    services = "\n".join(
        f'inline constexpr char {name}_SERVICE_UUID[] = "{uuid}";'
        for name, uuid in data["services"].items()
    )
    suffixes = "\n".join(
        f'inline constexpr char {name}_CHARACTERISTIC_SUFFIX[] = "{item["suffix"]}";'
        for name, item in data["characteristics"].items()
    )
    limits = data["limits"]
    return f"""// Generated by scripts/generate_protocol.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace radble {{

inline constexpr uint8_t PROTOCOL_VERSION = {data["protocolVersion"]};
inline constexpr char LIBRARY_VERSION[] = "{data["libraryVersion"]}";
inline constexpr size_t MAX_MESSAGE_BYTES = {limits["maxMessageBytes"]};
inline constexpr size_t STREAM_HEADER_BYTES = {limits["streamHeaderBytes"]};
inline constexpr size_t DEVICE_NAME_MAX_BYTES = {limits["deviceNameMaxBytes"]};
inline constexpr size_t OTA_FRAME_HEADER_BYTES = {limits["otaFrameHeaderBytes"]};
inline constexpr size_t OTA_CHUNK_MAX_BYTES = {limits["otaChunkMaxBytes"]};

{services}

{suffixes}

}}  // namespace radble
"""


def ts_module(data: dict) -> str:
    services = json.dumps(data["services"], indent=2)
    suffixes = json.dumps(
        {name: item["suffix"] for name, item in data["characteristics"].items()},
        indent=2,
    )
    operations = json.dumps(data["operations"], indent=2)
    errors = json.dumps(data["errors"], indent=2)
    limits = data["limits"]
    return f"""// Generated by rad-ble/scripts/generate_protocol.py. Do not edit.
export const RAD_BLE_LIBRARY_VERSION = {json.dumps(data["libraryVersion"])} as const;
export const RAD_BLE_PROTOCOL_VERSION = {data["protocolVersion"]} as const;
export const RAD_BLE_DEVICE_NAME_MAX_BYTES = {limits["deviceNameMaxBytes"]};
export const RAD_BLE_STREAM_FRAME_HEADER_BYTES = {limits["streamHeaderBytes"]};
export const RAD_BLE_OTA_FRAME_HEADER_BYTES = {limits["otaFrameHeaderBytes"]};
export const RAD_BLE_OTA_CHUNK_MAX_BYTES = {limits["otaChunkMaxBytes"]};

export const RAD_BLE_SERVICE_UUIDS = {services} as const;
export const RAD_BLE_CHARACTERISTIC_SUFFIXES = {suffixes} as const;
export const RAD_BLE_OPERATIONS = {operations} as const;
export const RAD_BLE_ERROR_CODES = {errors} as const;
"""


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"generated file is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp", type=Path, default=ROOT / "src" / "RadBleProtocol.generated.h")
    parser.add_argument("--typescript", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = load_manifest()
    write_or_check(args.cpp, cpp_header(data), args.check)
    if args.typescript:
        write_or_check(args.typescript, ts_module(data), args.check)


if __name__ == "__main__":
    main()
