// Generated by scripts/generate_protocol.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace radble {

inline constexpr uint8_t PROTOCOL_VERSION = 1;
inline constexpr char LIBRARY_VERSION[] = "1.0.0";
inline constexpr size_t MAX_MESSAGE_BYTES = 509;
inline constexpr size_t STREAM_HEADER_BYTES = 20;
inline constexpr size_t DEVICE_NAME_MAX_BYTES = 24;
inline constexpr size_t OTA_FRAME_HEADER_BYTES = 14;
inline constexpr size_t OTA_CHUNK_MAX_BYTES = 480;

inline constexpr char OSSM_SERVICE_UUID[] = "522b443a-4f53-534d-0001-420badbabe69";
inline constexpr char RADR_SERVICE_UUID[] = "522b443a-5241-4452-0001-420badbabe69";
inline constexpr char DTT_SERVICE_UUID[] = "522b443a-4454-5400-0001-420badbabe69";
inline constexpr char LKBX_SERVICE_UUID[] = "522b443a-4c4b-4258-0001-420badbabe69";

inline constexpr char PROTOCOL_INFO_CHARACTERISTIC_SUFFIX[] = "0002";
inline constexpr char CATALOG_CHARACTERISTIC_SUFFIX[] = "0003";
inline constexpr char DEVICE_NAME_CHARACTERISTIC_SUFFIX[] = "0004";
inline constexpr char DEVICE_IDENTITY_CHARACTERISTIC_SUFFIX[] = "0005";
inline constexpr char REQUEST_CHARACTERISTIC_SUFFIX[] = "1000";
inline constexpr char RESPONSE_CHARACTERISTIC_SUFFIX[] = "1100";
inline constexpr char STATE_CHARACTERISTIC_SUFFIX[] = "2000";
inline constexpr char ESSENTIAL_STATE_CHARACTERISTIC_SUFFIX[] = "2010";
inline constexpr char EVENT_CHARACTERISTIC_SUFFIX[] = "2100";
inline constexpr char SENSOR_STREAM_CHARACTERISTIC_SUFFIX[] = "2300";
inline constexpr char BUTTON_CHARACTERISTIC_SUFFIX[] = "3000";
inline constexpr char ENCODER_CHARACTERISTIC_SUFFIX[] = "3010";
inline constexpr char IMU_CHARACTERISTIC_SUFFIX[] = "3100";
inline constexpr char POWER_CHARACTERISTIC_SUFFIX[] = "3110";
inline constexpr char ANALOG_CHARACTERISTIC_SUFFIX[] = "3120";
inline constexpr char MAGNETIC_CHARACTERISTIC_SUFFIX[] = "3130";
inline constexpr char MOTION_CHARACTERISTIC_SUFFIX[] = "3140";
inline constexpr char CONNECTIVITY_CHARACTERISTIC_SUFFIX[] = "3150";
inline constexpr char INDICATOR_CHARACTERISTIC_SUFFIX[] = "4000";
inline constexpr char HAPTIC_CHARACTERISTIC_SUFFIX[] = "4010";
inline constexpr char AUDIO_CHARACTERISTIC_SUFFIX[] = "4020";
inline constexpr char DISPLAY_CHARACTERISTIC_SUFFIX[] = "4030";
inline constexpr char OTA_CONTROL_CHARACTERISTIC_SUFFIX[] = "5000";
inline constexpr char OTA_DATA_CHARACTERISTIC_SUFFIX[] = "5010";
inline constexpr char OTA_STATUS_CHARACTERISTIC_SUFFIX[] = "5020";

}  // namespace radble
